<?php
/*
Author:			This code was generated by DALGen version 1.1.0.0 available at https://github.com/H0r53/DALGen 
Date:			12/9/2017
Description:	Creates the DAL class for  subscription table and respective stored procedures

*/



class Subscription {

	// This is for local purposes only! In hosted environments the db_settings.php file should be outside of the webroot, such as: include("/outside-webroot/db_settings.php");
	protected static function getDbSettings() { return "DAL/db_localsettings.php"; }

	/******************************************************************/
	// Properties
	/******************************************************************/

	protected $Id;
	protected $Name;
	protected $Description;
	protected $TermTypeID;
	protected $Price;
	protected $ImgUrl;
	protected $CreateDate;
	protected $StatusTypeId;


	/******************************************************************/
	// Constructors
	/******************************************************************/
	public function __construct() {
		$argv = func_get_args();
		switch( func_num_args() ) {
			case 0:
				self::__constructBase();
				break;
			case 1:
				self::__constructPK( $argv[0] );
				break;
			case 8:
				self::__constructFull( $argv[0], $argv[1], $argv[2], $argv[3], $argv[4], $argv[5], $argv[6], $argv[7] );
		}
	}


	public function __constructBase() {
		$this->Id = 0;
		$this->Name = "";
		$this->Description = "";
		$this->TermTypeID = 0;
		$this->Price = 0;
		$this->ImgUrl = "";
		$this->CreateDate = "";
		$this->StatusTypeId = 0;
	}


	public function __constructPK($paramId) {
		$this->load($paramId);
	}


	public function __constructFull($paramId,$paramName,$paramDescription,$paramTermTypeID,$paramPrice,$paramImgUrl,$paramCreateDate,$paramStatusTypeId) {
		$this->Id = $paramId;
		$this->Name = $paramName;
		$this->Description = $paramDescription;
		$this->TermTypeID = $paramTermTypeID;
		$this->Price = $paramPrice;
		$this->ImgUrl = $paramImgUrl;
		$this->CreateDate = $paramCreateDate;
		$this->StatusTypeId = $paramStatusTypeId;
	}


	/******************************************************************/
	// Accessors / Mutators
	/******************************************************************/

	public function getId(){
		return $this->Id;
	}
	public function setId($value){
		$this->Id = $value;
	}
	public function getName(){
		return $this->Name;
	}
	public function setName($value){
		$this->Name = $value;
	}
	public function getDescription(){
		return $this->Description;
	}
	public function setDescription($value){
		$this->Description = $value;
	}
	public function getTermTypeID(){
		return $this->TermTypeID;
	}
	public function setTermTypeID($value){
		$this->TermTypeID = $value;
	}
	public function getPrice(){
		return $this->Price;
	}
	public function setPrice($value){
		$this->Price = $value;
	}
	public function getImgUrl(){
		return $this->ImgUrl;
	}
	public function setImgUrl($value){
		$this->ImgUrl = $value;
	}
	public function getCreateDate(){
		return $this->CreateDate;
	}
	public function setCreateDate($value){
		$this->CreateDate = $value;
	}
	public function getStatusTypeId(){
		return $this->StatusTypeId;
	}
	public function setStatusTypeId($value){
		$this->StatusTypeId = $value;
	}


	/******************************************************************/
	// Public Methods
	/******************************************************************/


	public function load($paramId) {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_subscription_Load(?)');
		$stmt->bind_param('i', $paramId);
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);

		while ($row = $result->fetch_assoc()) {
		 $this->setId($row['Id']);
		 $this->setName($row['Name']);
		 $this->setDescription($row['Description']);
		 $this->setTermTypeID($row['TermTypeID']);
		 $this->setPrice($row['Price']);
		 $this->setImgUrl($row['ImgUrl']);
		 $this->setCreateDate($row['CreateDate']);
		 $this->setStatusTypeId($row['StatusTypeId']);
		}
	}


	public function save() {
		if ($this->getId() == 0)
			$this->insert();
		else
			$this->update();
	}

	/******************************************************************/
	// Private Methods
	/******************************************************************/



	private function insert() {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_subscription_Add(?,?,?,?,?,?,?)');
		$arg1 = $this->getName();
		$arg2 = $this->getDescription();
		$arg3 = $this->getTermTypeID();
		$arg4 = $this->getPrice();
		$arg5 = $this->getImgUrl();
		$arg6 = $this->getCreateDate();
		$arg7 = $this->getStatusTypeId();
		$stmt->bind_param('ssidssi',$arg1,$arg2,$arg3,$arg4,$arg5,$arg6,$arg7);
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);
		while ($row = $result->fetch_assoc()) {
			// By default, the DALGen generated INSERT procedure returns the scope identity as id
			$this->load($row['id']);
		}
	}


	private function update() {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_subscription_Update(?,?,?,?,?,?,?,?)');
		$arg1 = $this->getId();
		$arg2 = $this->getName();
		$arg3 = $this->getDescription();
		$arg4 = $this->getTermTypeID();
		$arg5 = $this->getPrice();
		$arg6 = $this->getImgUrl();
		$arg7 = $this->getCreateDate();
		$arg8 = $this->getStatusTypeId();
		$stmt->bind_param('issidssi',$arg1,$arg2,$arg3,$arg4,$arg5,$arg6,$arg7,$arg8);
		$stmt->execute();
	}

	private static function setNullValue($value){
		if ($value == "")
			return null;
		else
			return $value;
	}

	/******************************************************************/
	// Static Methods
	/******************************************************************/



	public static function loadall() {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_subscription_LoadAll()');
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);
		if ($result->num_rows > 0) {
			$arr = array();
			while ($row = $result->fetch_assoc()) {
				$subscription = new Subscription($row['Id'],$row['Name'],$row['Description'],$row['TermTypeID'],$row['Price'],$row['ImgUrl'],$row['CreateDate'],$row['StatusTypeId']);
				$arr[] = $subscription;
			}
			return $arr;
		}
		else {
			die("The query yielded zero results.No rows found.");
		}
	}


	public static function remove($paramId) {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_subscription_Remove(?)');
		$stmt->bind_param('i', $paramId);
		$stmt->execute();
	}


	public static function search($paramId,$paramName,$paramDescription,$paramTermTypeID,$paramPrice,$paramImgUrl,$paramCreateDate,$paramStatusTypeId) {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_subscription_Search(?,?,?,?,?,?,?,?)');
		$arg1 = Subscription::setNullValue($paramId);
		$arg2 = Subscription::setNullValue($paramName);
		$arg3 = Subscription::setNullValue($paramDescription);
		$arg4 = Subscription::setNullValue($paramTermTypeID);
		$arg5 = Subscription::setNullValue($paramPrice);
		$arg6 = Subscription::setNullValue($paramImgUrl);
		$arg7 = Subscription::setNullValue($paramCreateDate);
		$arg8 = Subscription::setNullValue($paramStatusTypeId);
		$stmt->bind_param('issidssi',$arg1,$arg2,$arg3,$arg4,$arg5,$arg6,$arg7,$arg8);
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);
		if ($result->num_rows > 0) {
			$arr = array();
			while ($row = $result->fetch_assoc()) {
				$subscription = new Subscription($row['Id'],$row['Name'],$row['Description'],$row['TermTypeID'],$row['Price'],$row['ImgUrl'],$row['CreateDate'],$row['StatusTypeId']);
				$arr[] = $subscription;
			}
			return $arr;
		}
		else {
			die("The query yielded zero results.No rows found.");
		}
	}
}
