/*
Author:			This code was generated by DALGen version 1.1.0.0 available at https://github.com/H0r53/DALGen 
Date:			12/9/2017
Description:	Creates the statustype table and respective stored procedures

*/


USE topcryptopicks;



-- ------------------------------------------------------------
-- Drop existing objects
-- ------------------------------------------------------------

DROP TABLE IF EXISTS `topcryptopicks`.`statustype`;
DROP PROCEDURE IF EXISTS `topcryptopicks`.`usp_statustype_Load`;
DROP PROCEDURE IF EXISTS `topcryptopicks`.`usp_statustype_LoadAll`;
DROP PROCEDURE IF EXISTS `topcryptopicks`.`usp_statustype_Add`;
DROP PROCEDURE IF EXISTS `topcryptopicks`.`usp_statustype_Update`;
DROP PROCEDURE IF EXISTS `topcryptopicks`.`usp_statustype_Delete`;
DROP PROCEDURE IF EXISTS `topcryptopicks`.`usp_statustype_Search`;


-- ------------------------------------------------------------
-- Create table
-- ------------------------------------------------------------



CREATE TABLE `topcryptopicks`.`statustype` (
Id INT AUTO_INCREMENT,
Name VARCHAR(255),
Description VARCHAR(1025),
CONSTRAINT pk_statustype_Id PRIMARY KEY (Id)
);


-- ------------------------------------------------------------
-- Create default SCRUD sprocs for this table
-- ------------------------------------------------------------


DELIMITER //
CREATE PROCEDURE `topcryptopicks`.`usp_statustype_Load`
(
	 IN paramId INT
)
BEGIN
	SELECT
		`statustype`.`Id` AS `Id`,
		`statustype`.`Name` AS `Name`,
		`statustype`.`Description` AS `Description`
	FROM `statustype`
	WHERE 		`statustype`.`Id` = paramId;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE `topcryptopicks`.`usp_statustype_LoadAll`
()
BEGIN
	SELECT
		`statustype`.`Id` AS `Id`,
		`statustype`.`Name` AS `Name`,
		`statustype`.`Description` AS `Description`
	FROM `statustype`;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE `topcryptopicks`.`usp_statustype_Add`
(
	 IN paramName VARCHAR(255),
	 IN paramDescription VARCHAR(1025)
)
BEGIN
	INSERT INTO `statustype` (Name,Description)
	VALUES (paramName, paramDescription);
	-- Return last inserted ID as result
	SELECT LAST_INSERT_ID() as id;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `topcryptopicks`.`usp_statustype_Update`
(
	IN paramId INT,
	IN paramName VARCHAR(255),
	IN paramDescription VARCHAR(1025)
)
BEGIN
	UPDATE `statustype`
	SET Name = paramName
		,Description = paramDescription
	WHERE		`statustype`.`Id` = paramId;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `topcryptopicks`.`usp_statustype_Delete`
(
	IN paramId INT
)
BEGIN
	DELETE FROM `statustype`
	WHERE		`statustype`.`Id` = paramId;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `topcryptopicks`.`usp_statustype_Search`
(
	IN paramId INT,
	IN paramName VARCHAR(255),
	IN paramDescription VARCHAR(1025)
)
BEGIN
	SELECT
		`statustype`.`Id` AS `Id`,
		`statustype`.`Name` AS `Name`,
		`statustype`.`Description` AS `Description`
	FROM `statustype`
	WHERE
		COALESCE(statustype.`Id`,0) = COALESCE(paramId,statustype.`Id`,0)
		AND COALESCE(statustype.`Name`,'') = COALESCE(paramName,statustype.`Name`,'')
		AND COALESCE(statustype.`Description`,'') = COALESCE(paramDescription,statustype.`Description`,'');
END //
DELIMITER ;


